### ISSUE TITLE
String TypeError in version 1.6.1

### ISSUE THREAD

**Issue by emddudley** [jvarho/pylibscrypt#27]
Using Python 3.6.1 (64-bit) on Windows, and pylibscrypt 1.6.1:
```
(venv) C:\xyz>python
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pylibscrypt import scrypt_mcf, scrypt_mcf_check
>>> mcf = scrypt_mcf('Hello World')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\xyz\venv\lib\site-packages\pylibscrypt\pypyscrypt_inline.py", line 228, in scrypt_mcf
    return mcf_mod.scrypt_mcf(scrypt, password, salt, N, r, p, prefix)
  File "C:\xyz\venv\lib\site-packages\pylibscrypt\mcf.py", line 216, in scrypt_mcf
    if b'\0' in password:
TypeError: 'in <string>' requires string as left operand, not bytes
```

**Comment by jvarho** [comment]
On Python3 the interface expects a bytes object, no a string. I.e. `scrypt_mcf(b'Hello World')`

The error could be more helpful, however.
